p8105_hw1_ver2117
================
Varvy Rousseau
2022-09-20

``` r
#Loading in relevant packages for project
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
# Problem 1
#Used this code to download the data set penguins
data("penguins", package = "palmerpenguins")

#Getting a summary of descriptive statistics of variables 
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
#Getting the mean using the pull function to pull the variable out of the dataframe; this is for the mean of bill length of penguins

mean(pull(penguins, bill_length_mm), na.rm = TRUE)
```

    ## [1] 43.92193

The data contains the species of penguins, the island where they are
from and their bill depth, length, flipper length, sex, and the year

The species(Adelie, Chinstrap, Gentoo) found in the penguins dataset is
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie,
Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo,
Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Gentoo, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap,
Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstrap

The islands(Biscoe, Dream, Torgersen) found in the penguins dataset is
Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Torgersen,
Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Torgersen,
Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Torgersen,
Torgersen, Torgersen, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Dream, Dream, Dream, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Torgersen, Torgersen, Torgersen,
Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Torgersen,
Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Torgersen,
Torgersen, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Torgersen, Torgersen, Torgersen,
Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Torgersen,
Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Torgersen,
Torgersen, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe, Biscoe,
Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream,
Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dream

The mean(43.92mm) of bill length in mm found in the penguins dataset is
43.9219298

The mean(17.15mm) of bill depth in mm found in the penguins dataset is
17.1511696

The mean(200.9 mm) of flipper length in mm found in the penguins dataset
is 200.9152047

The mean(4202 g) of body mass of the penguins dataset is 4201.754386

The number of rows in the penguins dataset is 344 The number of columns
in the penguins dataset is 8

``` r
library(ggplot2)
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm)) +
  geom_point(aes(color = species))
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_ver2117_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

``` r
ggsave("Rplot.png")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

## Problem 2

``` r
prob2_df= tibble(
  r_sample = rnorm(10),
  vec_logical = r_sample > 0,
  vec_char = c("z", "y", "x", "w", "v", "u", "t", "s", "r","q"),
  vec_factor = factor(c("large", "medium","small", "large", "medium", "small", "large", "medium", "small", "large"), levels = c("small", "medium", "large"))
  )
```

``` r
# finding the mean of my data frame that I created using the mean and pull function of each variable

mean(pull(prob2_df, r_sample))
```

    ## [1] 0.5975868

``` r
mean(pull(prob2_df, vec_logical))
```

    ## [1] 0.8

``` r
mean(pull(prob2_df, vec_char))
```

    ## Warning in mean.default(pull(prob2_df, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob2_df, vec_factor))
```

    ## Warning in mean.default(pull(prob2_df, vec_factor)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

When trying to take the mean of each variable in my data frame, the mean
of the random sample is computed as 0.5975868

The mean of the logical vector is computed as
`mean(pull(prob2_df, vec_logical))`

The character vector cannot be computed as
`mean(pull(prob2_df, vec_char))`

The factor vector cannot be computed as
`mean(pull(prob2_df, vec_factor))`

``` r
#converting the logical, character and factor vector into numbers using the as.numeric function
as.numeric(pull(prob2_df, r_sample))
```

    ##  [1] -0.3020533  1.1863866  0.4167688  1.1077252  0.1372972 -0.5294957
    ##  [7]  2.4694921  0.4793472  0.5962702  0.4141294

``` r
as.numeric(pull(prob2_df, vec_logical))
```

    ##  [1] 0 1 1 1 1 0 1 1 1 1

``` r
as.numeric(pull(prob2_df, vec_char))
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(prob2_df, vec_factor))
```

    ##  [1] 3 2 1 3 2 1 3 2 1 3

After using `as.numeric(pull(prob2_df, vec_logical))`for the logical
vector the value of 0) is assigned to False and the value of 1 is
assigned to True. This allows us to interpret the logical vector in a
proportional sense.

When using the `as.numeric(pull(prob2_df, vec_char))`for the character
vector it converts the values to NA because it is not a logical or
numeric variabe which is the same for mean. It helps us show that this
is true.

I also used `as.numeric(pull(prob2_df, vec_factor))`for the factor
variable and it converted the levels into numbers 1,2, or 3 after I
assigned these levels a specific order. Previously, before I tried to
take the mean of the factor variable, R gave me a warning because the
differences between large and medium or large and small could not be
defined. So when I change the factor variable and levels to numbers, now
I can compute the mean.
